### ISSUE TITLE
How can I integrate or use Mecha v2 Comments?

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#10]
Hi @Tovic,

Mecha v2 has its own comment system, but I have not yet figured out where these comments are and how I can use them.

There is no "comment" in the `/lot` directory.

Are you telling me something about the comments?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
I am currently working on it.

![2017-03-28_104308](https://cloud.githubusercontent.com/assets/1669261/24388255/a7a8a998-13a3-11e7-8731-8da9961d8573.png)

**Comment by ghost** [comment]
Thank you and I'm looking forward to it.
