### ISSUE TITLE
How Can I Implement Thumbnails on Article Page

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#11]
Hi @Tovic,

I have not quite understood this topic at http://mecha-cms.com/snippet/field-images.

I have hooked up thumbnails in index.php. Then I have in the pages.php this code. 

``` .php
<?php Shield::get('header'); ?>
<main>
  <?php echo $message; ?>
  <?php foreach ($pages as $page): ?>
  <article id="page-<?php echo $page->id; ?>">
    <header>
      <h3>
        <?php if ($page->link): ?>
        <a href="<?php echo $page->link; ?>" rel="nofollow" target="_blank"><?php echo $page->title; ?> &#x21E2;</a>
        <?php else: ?>
        <a href="<?php echo $page->url; ?>"><?php echo $page->title; ?></a>
        <?php endif; ?>
      </h3>
    </header>
    <?php if (!empty($page->images)): ?>
    <?php echo HTML::img($page->images[0]); ?>
    <?php endif; ?>
    <section><?php echo $page->description; ?></section>
    <footer></footer>
  </article>
  <?php endforeach; ?>
  <nav><?php echo $pager; ?></nav>
</main>
<?php Shield::get('footer'); ?>
```

This is the whole code.

No thumbnails are displayed on the article page >> https://mechacms.wpzweinull.ch/article

But I have an image in the article already >> https://mechacms.wpzweinull.ch/article/erste-bild-url-im-artikel-wird-auf-der-artikel-seite-als-thumbnail-angezeigt

What am I doing wrong?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Replace this part:

~~~ .php
  <?php if (!empty($page->images)): ?>
  <?php echo HTML::img($page->images[0]); ?>
  <?php endif; ?>
~~~

With this, and tell me what you see:

~~~ .php
<?php __test__($page->images); ?>
~~~

**Comment by ghost** [comment]
I see that:

```
<?php

array (
  0 => 'https://wpzweinull.ch/wp-content/uploads/2017/04/mecha-v2-cms-artikel-startseite-im-blog-frontend-1.jpg',
)

?>
```

**Comment by taufik-nurrohman** [comment]
Then it should works as expected &rarr; https://github.com/mecha-cms/genome/blob/73da742b8354f3a1c8d89c054290ad93953fab45/engine/plug/h-t-m-l.php#L13&L21

Weird. What will happen if you do:

~~~ .html
<img src="<?php echo $page->images[0]; ?>" alt="">
~~~

**Comment by ghost** [comment]
Ok, cool, I've been successful with this PHP code.

I have inserted this in pages.php.

```
 <?php if (!empty($page->images)): ?>
  <?php echo HTML::img($page->images[0]); ?>
  <?php else: ?>
  <img src="<?php echo $page->images[0]; ?>" alt="">
  <?php endif; ?>
```

**Comment by taufik-nurrohman** [comment]
That was not the expected result. The `else` block is used to handle the case if there is no images at all, so you could set a default image URL as a backup. I realize that the problem cames from the lack of the PHP magic method. Caching the `$page->images` value to a variable before checking with the `empty` construct should fix the issue:

~~~ .php
<?php $images = $page->images; ?>
<?php if (!empty($images)): ?>
<?php echo HTML::img($images[0]); ?>
<?php endif; ?>
~~~

**Comment by ghost** [comment]
Thanks @tovic,

Yes, I am clearly missing the knowledge of a PHP programmer. But I have now taken this code and inserted it. Thumbnails in pages.php are displayed.

With "no-image.png" I also understood that it serves to if you have no pictures in the article. Then you can display the default image. This can be useful.
