### ISSUE TITLE
Comments Not Workend on mecha-cms.com

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#13]
Hi @tovic,

Unfortunately your comments do not go at http://mecha-cms.com.

After submitting the comment, a PHP code is displayed, but the comment does not appear.

Can you please take a look.

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Good morning. I am currently working on fixing the little bug on the `comment-notify` plugin.

**Comment by ghost** [comment]
Ok, thanks for your quick reply. Then I wait until you can solve the problem and try to comment on it.
