### ISSUE TITLE
How can I Disable Comments on the Index Home Page?

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#14]
Hi @Tovic,

You recently reported in the blog that you can disable comments on special pages.

How can I set comments on the Index HomePage to inactive? I think I would like to use the HomePage as a traditional blog home and so it would be good if it can not be commented.

Then I wait for your feedback and thanks in advance.

**Comment by taufik-nurrohman** [comment]
Try http://mecha-cms.com/snippet/comment-x-static

**Comment by ghost** [comment]
Hi,
Thanks for the hint and in what file do I have to insert the code? If I do this in the index.php of the Shield, then the Blog HomePage is no longer accessible.

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Just wrap the comments snippet in `page.php` with that `if` statement.

**Comment by ghost** [comment]
Thanks, this has now done in the normal shield. Comment in the root directory of the blog homepage are no longer displayed.
