### ISSUE TITLE
I Now Have Two Home Pages in Mecha CMS - I Just Need One

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#15]
Hi @Tovic ,

Thanks for the new shield, which I already installed. I have now however two Homepages and look at the please under https://mechacms.wpzweinull.ch/index. Under "Home" is the blog homepage and then still under `/index`. How can I have a home page in the root directory?

The page under `/index` can be deleted. I also have a blog.

Thank you.

**Comment by ghost** [comment]
I have solved the problem now and created in the backend at the homepage my content and "index" removed. Now it's a conventional page with info. It had not occurred to me, but I think it was easy.

**Comment by taufik-nurrohman** [comment]
There is a configuration file in `lot\shield\normal\state\config.php`. Change the `path` value from `article` to `index`.

**Comment by ghost** [comment]
OK, I have now done this differently. I know, however, that you can play with Mecha CMS something, so you can customize it and like it.

Thanks for the tips and hints.
