### ISSUE TITLE
You, Tovic, Expects a Little Donation From Me in the Next Few Days

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#16]
Hi @tovic ,

I thought about it a bit and wanted to support the Mecha CMS project again. A small donation in the amount of 15 USD I just passed and as soon as the money was transferred from my bank to PayPal, you get this donation.

Of course gladly done and I can well imagine that an OpenSource project can not be built up by itself. Since I am very happy with this CMS in v1 and v2, I would like to support it a bit.

With such large CMS as Wordpress and Joomla or Drupal, there are a lot of voluntary developers, but the Mecha CMS has yet to be brought to Germany and presented to the Webusern.

Maybe I can make a small contribution with my Mecha Blog and GitHub activities.

You will be even more motivated to develop and develop. I'm looking forward to new snippets, extensions, plugins and hooks. Much I will try and use in my own blog.

Then tell me by mail at power_sash@gmx.net briefly, when the money with you in PayPal has arrived.

Thank you!

**Comment by taufik-nurrohman** [comment]
I have got the email. Thanks a lot.
