### ISSUE TITLE
How do I get the Panel the Way it looks in your Blog Post

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#17]
Hi @Tovic,

I have just seen the blog post at http://mecha-cms.com/reference/extension/panel. How did you manage that there are already tabs for "Shield" and "Extend" in the panel.

I do not have it yet. In the FTP account under `/lot/shield` are two shields with me. "Extend" -Tab I have not yet.

I just uploaded the last branch. Here I have the directory `/engine` overwritten with new files. Then I have uploaded extensions like Panel and Comments.

Still, it looks different with me and so does.

![mecha-v2-cms-panel-look](https://cloud.githubusercontent.com/assets/7885632/25178579/a1abc3d0-2506-11e7-88eb-6ec5d94f4e78.png)

**Comment by taufik-nurrohman** [comment]
No, that is just a _mockup_. A concept for the finished results. That&rsquo;s why I still mark it as &ldquo;coming soon&rdquo;.

**Comment by ghost** [comment]
Ok, then I know more about it. Thank you.
