### ISSUE TITLE
Social Share Buttons for Mecha V2 CMS

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#18]
Will you still port the Social Share Buttons Plugin or the Extensions of Mecha v1 to Mecha v2 or is it for the first time not thought?

Thanks in Advance.

**Comment by taufik-nurrohman** [comment]
I&rsquo;m still stuck with the share counter.

**Comment by ghost** [comment]
Ok, I have long patience and when it is time, then set the share buttons.

**Comment by ghost** [comment]
Hi,

I have now installed the plugin with social share buttons, but sharing the content still does not work properly.

Please try to share this post in Twitter >> https://mechacms.wpzweinull.ch/article/neues-mecha-v2-cms-shield-ist-erschienen-hier-inspired

It is taken as text the description of the page and since it is with me always longer, is not so for Twitter. TwitterCards Plugin I have also just installed and in the config.php my nickname "blogsash" registered. This is for Twitter.

What do I forget here or what do I do wrong?

For Facebook and Google Plus you have to have screenshots and pictures in the posts. Then it would be optimal.

**Comment by taufik-nurrohman** [comment]
Will fix this issue next time. Could you move this issue to the `extend.plugin.share` repository instead? Thanks.
