### ISSUE TITLE
Question: Can I Display the Number of Comments in the Index Page in the Teaser

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#19]
Hi @Tovic,

I have such a question. Can I view the number of existing comments on the index page in the article teaser? That would be interesting and desirable right next to the views.

I'll show you a screenshot.

For the blog readers this would be an indication that the posts were already commented and possibly it increases the attractiveness of the whole blog: smile:

Then I wait for your feedback.

![mecha-v2-cms-comments-in-the-index-page](https://cloud.githubusercontent.com/assets/7885632/25386366/6f087f8e-29c7-11e7-86bb-d10bff850219.png)

Thank you!

**Comment by taufik-nurrohman** [comment]
It should, but I can&rsquo;t make it work with the current version. I have fixed the bug on [this commit](https://github.com/mecha-cms/extend.comment/commit/63dc5ea797e887fdc8bf9aecdcbc2b8281bddeaf). You can now update the comment extension and then replace the `.post-property` part with this:

~~~ .php
    <p class="post-property">
      <time class="post-time" datetime="<?php echo $page->date->W3C; ?>">
        <?php echo $page->date->{str_replace('-', '_', $site->language)}; ?>
        <?php echo $page->view ? ' &#x00B7; ' . $page->view : ""; ?>
        <?php echo $page->comments && isset($page->comments->text) ? ' &#x00B7; ' . $page->comments->text : ""; ?>
      </time>
    </p>
~~~

**Comment by ghost** [comment]
Thank you, it worked well and now my blog readers see that the posts were already commented here and there.
