### ISSUE TITLE
Your Comments in Mecha-cms.com not worked

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#20]
Hi @tovic ,

I just wanted to comment on the blog post at http://mecha-cms.com/article/c-k-editor-web-spell-check-enable in the official Mecha blog.

After the correct captcha and sending the comment, you will be redirected to the Mecha v1 and the blog, but the comment will not be created.

Therefore, I think times, that something is wrong, because comment is not possible.

By the way Thanks for the tutorial and the browser Spellcheck I have just made. It is very helpful and you can blog very long blogposts without any problems.

Please look at the comments with you.

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Ah I know the problem. Sorry. Will fix this soon.

**Comment by ghost** [comment]
OK, thank you!
