### ISSUE TITLE
Would a Forum Extension possible with the Mecha v2 CMS

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#22]
Hi @Tovic ,

I wanted to ask you if it would be possible to develop a forum extension for the Mecha v2? It can be a small forum solution with user login and the forums, categories, possibly also sub-forums.

Gravatar support should be possible.

I do not know, if you ever thought in the direction? Maybe you want to leave the Mecha CMS at the blog and as a forum you can take an independent forum solution.

So I just wanted to ask :)

Thank you!

**Comment by taufik-nurrohman** [comment]
That was a huge task. I have thought about that since `v1.x.x` but still not possible to achieve.

**Comment by ghost** [comment]
OK thanks! Maybe it will be possible someday, although I know that it is technically very complicated. A forum solution is not a blog and all components have to be right.
