### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#23]
Hi @tovic,

Have discovered a bug that looks like this.

    Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /xxxxxxxxx/mechacms.wpzweinull.ch/engine/kernel/genome.php on line 63

Perhaps I have to make a few updates of the extensions, plugins or anything else.

I have just taken some of the repos here and updated my blog.

Otherwise look good and thanks for all the updates.

**Comment by taufik-nurrohman** [comment]
Update your [log in/out link snippet](http://mecha-cms.com/snippet/log-in-a). I have changed the `User::current()` method to be `User::get()`.

**Comment by ghost** [comment]
Thanks, it worked. Everything is good and I can devote myself to the blog with even more joy.

The issue can be closed.

**Comment by taufik-nurrohman** [comment]
Lastly, update your code in `lot\shield\normal\index.php` from `User::current()` to `User::get()`.

**Comment by ghost** [comment]
Thank you, it has just been done. Everything works as before. Very beautiful!
