### ISSUE TITLE
Good Work, Tovic - for Extensions and Plugins in the Backend

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#24]
Hi @Tovic,

Good work you have done this time and I have just uploaded the panel extension. Are the settings for each extension added? As it looks, I can not manage extensions and plugins in the GUI yet.

Thanks in advance.

![mecha-v2-cms-feed-extension-settings](https://user-images.githubusercontent.com/7885632/28996703-a34d425a-7a05-11e7-86d4-10c829d744d5.png)

**Comment by taufik-nurrohman** [comment]
![](https://user-images.githubusercontent.com/1669261/29003457-2d389254-7ae1-11e7-9c97-33eac4a7ff01.png)

There are a lot of API refactoring recently. Try to install the fresh versions. I have tested it in my environment. [Here, are some of the screen captures&hellip;](https://github.com/mecha-cms/extend.panel/issues/7)
