### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /mechacms.wpzweinull.ch/engine/kernel/genome.php

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#25]
Hi,

Just have problems after the update.

I have deleted the directory `/engine` and uploaded the new files.

Also, what you updated here today on extensions, I have also deleted the old and uploaded new files.

Something is back with `login/logout` link, although I have it up-to-date.

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /xxxxxxxxxx/mechacms.wpzweinull.ch/engine/kernel/genome.php on line 63`

`Warning: Cannot modify header information - headers already sent by (output started at /xxxxxxxmechacms.wpzweinull.ch/engine/kernel/genome.php:63) in /www/htdocs/w0103f82/mechacms.wpzweinull.ch/engine/kernel/cookie.php on line 53`

What could that be?

P.S. Browser cache also deleted multiple times in Google Chrome using the tool Ccleaner.

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Too less information. The error may be generated from a class that was extended to the `Genome` class with its own `__callStatic` property that does not have default `$lot` value as array:

~~~ .php
abstract class Genome {
    public static function __callStatic($kin, $lot = []) {}
}
~~~

~~~ .php
// Here, the `$lot` argument is not compatible with `$lot` value from the parent class.
class Foo extends Genome {
    public static function __callStatic($kin, $lot) {} // ←
}
~~~

This pattern must be exists somewhere in the files.
