### ISSUE TITLE
Article Home is displayed twofold

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#26]
I have a problem with the Article homepage.

It is displayed twice at https://mechacms.wpzweinull.ch/article.

I did not make any further updates for the first time and it is an FTP backup of the whole installation.

But I do not know why it is so suddenly.

Could you help me.

Thanks in advance.

**Comment by ghost** [comment]
Will report me here again. I have now uploaded a clean FTP backup and now everything works again.

But I have big concerns when I have to install your updates from now on.

There will be mistakes again or how do you see that?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Next time I will create a blog post about tutorial on how to properly update Mecha manually.

**Comment by taufik-nurrohman** [comment]
Fixed now. This is my mistake.

**Comment by ghost** [comment]
Thanks a lot for this. Therefore did not want to update for the first time.

Your tutorial, how to properly update, I look at me nevertheless.
