### ISSUE TITLE
NoFollow-Attribute on all external Links in Mecha v2 CMS

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#27]
Hi,

I would like to put all external links on noFollow. How can I realize that all links are provided with noFollow.

With the plugin link in the Ckeditor does not go and I would have to add an extended dialog tool as a plugin.

Would that be possible or which nofollow solution would work?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Generate them in the output instead.

http://mecha-cms.com/snippet/a-rel-auto
