### ISSUE TITLE
How can I show Code Snippets more nicely - HTML format

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#28]
Hi,

I have a question. How can I make code more attractive in content? If you look at this post under https://mechacms.wpzweinull.ch/article/mecha-v2-cms-nofollow-attribut-bei-external-links-wie-geht-das, so I could the code Snippet only with `<code> ..... content ..... <code>`.

I do not like it and I would like to take it in the `<pre>` -tags.

This I have in the ckeditor but not and only `<code>`.

How can I implement it or do I have to add the style with `<pre>`?

Thanks in advance.

**Comment by ghost** [comment]
I have it realized and have taken the code as a block. It is displayed with a black background, which is slightly better than before.

But will not there be `<pre>` tags in the ckeditor?

**Comment by taufik-nurrohman** [comment]
That was a `<pre>` tag actually, I just don&rsquo;t apply monospaced font to it as the way the code span look like. To make a semantic code block markup, first select the text you want to style, then click the _Block_ style, then click again _Code_ style, so that your text will be wrapped by both `<pre>` and `<code>` tag.

For better code snippet, there is a plugin with the same name in the **CKEditor** repository.

**Comment by ghost** [comment]
Thank you, I think I will distinguish code as the ckeditor allows it.

But I have been watching strange things for several days. If I add to the config.php "ExtraPlugins", the Editior in the GUI is no longer displayed. So now I can not add Scayt again.

The editor is simply not accessible, as I make something in the config.php.

Can you observe this or what am I doing wrong?

My config.php looks like this now.

``` php
<?php

return [
    'skin' => 'moono-lisa',
    'uiColor' => '#ffffaa',
    'toolbar' => [
        ['Undo', 'Redo'],
        ['Bold', 'Italic', 'Underline', 'RemoveFormat'],
        ['SpecialChar', 'Link', 'Image', 'Table', 'HorizontalRule'],
        ['NumberedList', 'BulletedList', 'Blockquote', 'Indent', 'Outdent'],
        ['Styles'],
        ['Scayt']
    ],
    'extraPlugins' => 'scayt,codesnippetgeshi,codemirror',
    'height' => '30em',
    'filebrowserImageBrowseUrl' => '/' . Extend::state('panel', 'path', 'panel') . '/::g::/asset?layout=0',
    'filebrowserImageUploadPath' => ASSET
];
```

Are there any errors?

**Comment by taufik-nurrohman** [comment]
Every plugin has their own dependencies. Make sure that before you install any plugin you also have installed the plugin dependencies for that.

Moved to [@mecha-cms/extend.c-k-editor](https://github.com/mecha-cms/extend.c-k-editor).
