### ISSUE TITLE
Plugin Request: Download Plugin or System

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#29]
Hi @tovic ,

I have a plugin request and how would it be with the download plugin, so you can offer ZIP files for download. It would be very interesting if it were possible.

Did you think about such a plugin?

Thanks in advance.

P.S. Backup plugin you wanted to write

**Comment by taufik-nurrohman** [comment]
Depending on what you mean here, whether it is about a simple download plugin which will convert folder into a ZIP file or it&rsquo;s related to &ldquo;downloading extensions and plugins via control panel&rdquo;?

**Comment by taufik-nurrohman** [comment]
About the backup extension/plugin, I need to finish the stable version of this [package](https://github.com/mecha-cms/extend.package) extension. This is an old class used by Mecha `v1.x.x` and I think it would be better to extend some methods to the `File` or `Folder` class instead of making another class (`Package`) Example:

~~~ .php
// extract
Package::extract('path\to\file.zip');

// pack
File::pack([
    'path\to\file-1.txt',
    'path\to\file-2.txt'
]);

// pack
Folder::pack('path\to\folder');
~~~

**Comment by ghost** [comment]
I thought of a download plugin where I can upload my own files and ZIP Archives in Mecha and then download them on a separate page. Of course it goes without such a Plugin.

But that you could download Extensions and Plugins from the control panel of Github, sounds very interesting 😄

**Comment by taufik-nurrohman** [comment]
> I thought of a download plugin where I can upload my own files and ZIP Archives in Mecha and then download them on a separate page.

That&rsquo;s easy. I can even make it as a very short code snippet. As a plugin, maybe there should be a feature to count the number of downloads (I just need to implement the [page view](https://github.com/mecha-cms/extend.plugin.view) plugin into this).

> But that you could download Extensions and Plugins from the control panel of Github, sounds very interesting :smile:

That requires a dedicated server and extra costs if the files you want to download recieved from the Mecha CMS server. I can&rsquo;t do that. Taking a ZIP file from GitHub is easy as we already know the URL pattern, but I ever more think about file sync and such.

**Comment by ghost** [comment]
Thanks for the tips and hints. Yes, such a snippet would be very good for this task. And of course I want the individual downloads to be counted.

OK, I can understand this well with the second thing. We have Github for everything and can deal with downloads and "git clone" super. That's enough.

**Comment by taufik-nurrohman** [comment]
https://github.com/mecha-cms/extend.plugin.download

**Comment by ghost** [comment]
Thanks for the plugin, but what am I doing wrong?

Please visit https://mechacms.wpzweinull.ch/files. Thank you.

**Comment by taufik-nurrohman** [comment]
Don&rsquo;t you have [block extension](https://github.com/mecha-cms/extend.block) installed, or, haven&rsquo;t you updated the block extension recently? I have found little bug in this extension so I have updated the extension recently. &rarr; [fix missing `$lot` parameter](https://github.com/mecha-cms/extend.block/commit/de38c03a67dd7eb08a88b766702558f212845353#diff-f8d8ec9dc986474ee30c0c976f87db1aR28)

> **PS:** Moved to [@mecha-cms/extend.plugin.download](https://github.com/mecha-cms/extend.plugin.download)

**Comment by ghost** [comment]
Thank you @tovic,

I have just uploaded the block extension and the download plugin in a new version. Now everything works as it should be.

But so I say times that the download plugin is very cool and unfortunately I offer from myself from only one language file for an OpenSource forum in German.

Otherwise I would offer everything possible to download.

Good work at the Download Plugin 👍

**Comment by taufik-nurrohman** [comment]
It&rsquo;s okay. Next time, consider to write the issues related with the plugin to the original plugin repository instead, so that the issue tracking will be neat and related to each other. Don&rsquo;t worry, I will always be notified by GitHub.

**Comment by tovic** [comment]
It&rsquo;s okay. Next time, consider to write the issues related with the plugin to the original plugin repository instead, so that the issue tracking will be neat and related to each other. Don&rsquo;t worry, I will always be notified by GitHub.
