### ISSUE TITLE
Would be a "Up-Button" as a Plugin possible

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#30]
Hi @Tovic,

I wanted to ask you if it would be possible to develop an up-button as a plugin. I have in my blog also times very long pages and I wish that the reader without much to scroll to the upper section of the page can get.

Would such a plugin or an extension possible?

Then I wait for your early feedback.

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Added to my TODO list.

**Comment by ghost** [comment]
Thanks @tovic !!
