### ISSUE TITLE
Recoverable fatal error: Method User::__toString() must return a string value

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#32]
Hi @tovic ,

I will still see this error on the pages.php.

    Recoverable fatal error: Method User::__toString() must return a string value in 
    /xxxxxxxxx/mechacms.wpzweinull.ch/lot/shield/normal/pages.php on line 7

Does this have something to do with the Shield Normal and with Mecha v2?

Can you see this please.

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Try to delete the user file then create again. The string output should be generated by the `author` field by default, but if for some reasons (I don&rsquo;t know), the `author` data returned as something that is not a string, then this error will happen. Or, maybe because there is no `author` field at all so that the output will return `null` as it is the default value.

**Comment by ghost** [comment]
Unfortunately it did not work. How was the URL in the browser to create a new user?

Then I empty the `/user` directory and create a new user in the browser. Maybe it will work.

Thanks in Advance.

**Comment by taufik-nurrohman** [comment]
Delete the `user` folder, so that you can access the login page again to create the initial user file.

**Comment by ghost** [comment]
Thank you! Now I have two users in the Mecha blog, but unfortunately the blog is no longer accessible at https://mechacms.wpzweinull.ch/.

What am I doing wrong? All articles are determined by the `author/user`. If now a new user, we do not see anything in the blog.

How can I fix it?

Thanks in advance.

**Comment by ghost** [comment]
Backend is OK!

**Comment by ghost** [comment]
Hm ... strange. I now need to update all articles and blog posts in the backend. The previous error under `/article` is now gone.

But maybe it works so after I created a new user.
