### ISSUE TITLE
Support for Mecha CMS via Banner on Yaf-forum.de

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#34]
Hi @tovic 

I've placed the Mecha CMS as a partner in my CMS / Blogger forum at https://yaf-forum.de. In this way, I would like my German readers to get to know your project and see what happens in the Mecha development.

My pleasure!!

P.S. The banner is also placed in the right sidebar of the forum and the link to Mecha-cms.com.

**Comment by taufik-nurrohman** [comment]
Thanks. Really appreciate it!
