### ISSUE TITLE
How can I embed Youtube Videos

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#35]
Hi @tovic ,

is there any way to deal with the Youtube videos at Genome Branch and integrate them into the pages?

This is of interest to me because I have a Youtube tutorial channel recently and would like to report about it in the Mecha CMS Blog. Maybe it needs a plugin, but unfortunately I can not integrate it into the Ckeditor.

Somehow the new Config is not accepted. I added the "Video-Embed" tool. Sadly, it's not possible.

Thanks in Advance.

**Comment by taufik-nurrohman** [comment]
It would be possible without WYSIWYG that stripped the original embed HTML, or &hellip;

Two method to embed external widget:

 1. Using _Block_ extension that parses `[[youtube]]` to its original HTML embed code.
 2. Using plain PHP regex that able to convert _YouTube_ URL into HTML embed code.

Which one do you think appropriate for _Mecha_?

**Comment by ghost** [comment]
Hi,

I think with the number 2, so you only have to enter a Youtube URL. This can then be videos. That would be interesting.

Is this already possible or do you still have to prepare? I think you have to prepare it in Mecha or ...?

Thank you in Advance.

**Comment by taufik-nurrohman** [comment]
Yes that&rsquo;s possible. I just have to surf the internet to find the best regex and do the generic `page.content` hook.

**Comment by taufik-nurrohman** [comment]
Moved to [@mecha-cms/extend.plugin.youtube](https://github.com/mecha-cms/extend.plugin.youtube)
