### ISSUE TITLE
How to Embed Dailymotion Videos in a Mecha Page

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#36]
Hi @tovic ,

would a new extension for embedding the Dailymotion videos possible?

Such a video would be with me for example under http://www.dailymotion.com/video/x69kio0

It will probably be similar to what youtube videos did. So from the Dailymotion URL in the browser to convert a video.

Would that be possible with such a new extension?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Also with _Vimeo_ video.

**Comment by ghost** [comment]
Yes, I am also on Vimeo and would like to work permanently with these three sharing services like Youtube, Dailymotion and Vimeo.

It would be enough if I can embed individual videos of these services and providers in Mecha.

Thank you in Advance.

**Comment by ghost** [comment]
Hi Tovic,

I've added video embed tool to the ckeditor and can embed videos. But look at this screenshot! The video player height is very small and I still do not know if that makes the Mecha CMS or where the origin.

Do you have an idea maybe?

Thanks in advance.

I embed the Dailymtoion video via video URL. That's how it worked today.

![dailymotion-video-mechav2cms-error](https://user-images.githubusercontent.com/7885632/33528241-946eceaa-d85d-11e7-95bb-4b71572f924a.jpg)

**Comment by taufik-nurrohman** [comment]
That&rsquo;s because of the default CSS `<iframe>` from the _Normal_ shield. To fix this, wrap the iframe with this markup:

~~~ .html
<div class="fluid-video">YOUR EMBED CODE HERE</div>
~~~

**PS:** https://github.com/mecha-cms/extend.plugin.dailymotion
