### ISSUE TITLE
Adsense disappears after Plugin Installation

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#38]
Hi @tovic ,

For me after the plugin installation Adsense is no longer displayed. When I take the RAPIC plugin, only the yellow bar is visible. Can you also watch this with you?

After I installed the scroll plugin, so it is.

To view my new/old Mecha website at http://mecha.liebrechts-portfolio.de/

I do not know exactly what it can be. I just noticed the days.

Maybe you can help me.

Thanks in Advance.

**Comment by taufik-nurrohman** [comment]
No idea currently (can&rsquo;t see any error messages in the console). Will consider this as a bug when I have the clues.

**Related:** https://github.com/mecha-cms/extend.plugin.js-scroll

**Comment by ghost** [comment]
You can close this issue and adsense will be displayed!

> You can close this issue, (somehow) the adsense already displayed! ;)
