### ISSUE TITLE
Cannot Login as exist User

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#39]
Hi @Tovic,

I've finally made an update to the new developer version of Github. So my Mecha CMS blog is under https://mecha.liebrechts-portfolio.de/ and unfortunately I can not log in as an existing user.

All extensions and plugins I have replaced by new versions of Github, otherwise the blog would not be available in the browser. I had already experienced that today with the old Mecha version.

If I want to log in, nothing happens. There are no errors displayed or I can somehow debug it.

The login is under `/panel/::g::/enter`, as far as I know. How can I find errors if nothing is displayed and login does not work anymore with old login data.

Thanks in Advance.

**Comment by taufik-nurrohman** [comment]
Delete current user `pass.data` manually then login again with the old (current) user name.

~~~ .txt
.\www\lot\user\{$user}\pass.data
~~~

**Comment by ghost** [comment]
This does not work and I have now completely deleted the old user to create a new one. After the input of the user and the new password, nothing happens and the user is not created.

I do not know if it's a server issue for me or something else.

**Comment by ghost** [comment]
Have now made a completely new Mecha 2.0.0 installation and unfortunately I get this error displayed in the backend when I am under Page, Shield or User.

`Server Error
503
Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.`

How can I debug what it might be?

In addition, I use ModSecurity as a server firewall and have already approved three new rules.

The frontend of the blog with the Normal Shield is already displayed, but unfortunately in the backend again and again the same error.

Could you help me.

Thanks in Advance.

P.S. Does the error have anything to do with mecha or just my server?

**Comment by taufik-nurrohman** [comment]
Test it again. Follow these steps:

 - Install a fresh Mecha package.
 - Add fresh `user` and `panel` extension.
 - Now visit the front-end then back-end page to check!

**Comment by ghost** [comment]
Thanks for this @tovic ,

I can call the "Page" tab in the backend and the contents are displayed.

The frontend with the "document" shield is also displayed.

Now I would like to install all sorts of plugins and extensions and set up my new Mecha website.

If I notice something, I'll let you know.

Thank you for dedicating yourself to your project so soon before New Year's Eve. I really appreciate that and wish you and your loved one all the best for the new year 2018 👍

**Comment by taufik-nurrohman** [comment]
It is 22:40 here 😉

**Comment by ghost** [comment]
Here is 31.12.2017 17:18 pm 🎆
