### ISSUE TITLE
How Can I Update Mecha V2 when GitHub Has Been Further Developed

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#4]
Hello Developers,

You are developing this MechaCMS more and more. How can I update my installation. The directory `/lot` probably I should not overwrite. The directory `/engine` is probably always overwritten with new files.

Or how do I make an intermediate update correct?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Take out these folders including its contents to be restored later once you have successfully update everything:

~~~ .txt
engine\log\user
lot\asset
lot\comment
lot\page
lot\shield\your-custom-shield
lot\state\config.php
lot\tag

**Comment by ghost** [comment]
OK, thank you for this hints and the information. Then I can next time backup these directories and restore later.
