### ISSUE TITLE
Contact Page showing Errors

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#41]
Hi Tovic,

I have now arrived at the previously not working Contact Page and Apache Error Log show me these errors.

`PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function __url__() in /xxxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/lot/extend/plugin/lot/worker/block.url/index.php:6\nStack trace:\n#0 /xxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/lot/extend/block/index.php(28): fn_block_url('[[contact]]', Array, Object(Page), 'content')\n#1 /xxxxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/engine/kernel/hook.php(81): fn_block('[[contact]]', Array, Object(Page), 'content')\n#2 /xxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/engine/kernel/hook.php(87): Hook::fire('*.content', Array)\n#3 /xxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/engine/kernel/page.php(116): Hook::fire(Array, Array)\n#4 /xxxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/engine/kernel/page.php(70): Page->__get('content')\n#5 xxxxxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/engine/kernel/page.ph...\n', referer: https://mecha.liebrechts-portfolio.de/panel/::g::/page/contact     `            

Can you see it in 2018?

Thanks in Advance.                                              `

**Comment by taufik-nurrohman** [comment]
It&rsquo;s from the `block.url` plugin.

**Comment by ghost** [comment]
OK, this Plugin i have disabled.

Now this Apache Error!!

`AH01071: Got error 'PHP message: PHP Fatal error:  ob_start(): Cannot use output buffering in output buffering display handlers in /xxxxxxxxx/liebrechts-portfolio.de/mecha.liebrechts-portfolio.de/lot/extend/plugin/lot/worker/contact/index__.php on line 16\n', referer: https://mecha.liebrechts-portfolio.de/ `

On Contact Page showing a Blank Page.
