### ISSUE TITLE
Extension Suggestion - Google XML Sitemap

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#43]
Hi @tovic ,
I have thought about something further and I always appreciate your support very much. Did you ever think about a new extension like Google XML Sitemap, which will be generated as sitemap.xml in the root of the website?

Then you can submit the sitemap in the Search Console and get better indexed and even the big search engines would have access to it. I wish for this extension and maybe it would be feasible to develop something like this.

What do you think about it?

Thank you, Alex.

**Comment by taufik-nurrohman** [comment]
This should be added to the [feed](https://github.com/mecha-cms/extend.feed) extension long time ago. But I need to learn about the (probably) W3C standard for XML sitemap. Especially about how to reference nested pages in the XML file, so we could make the search engine bots read our sitemap partially (no need to load the whole pages at the same time).

**Update:** https://www.sitemaps.org/protocol.html#index

**Comment by ghost** [comment]
Okay, thanks for your answer. Then take your time, think that the implementation is not easy. But you are a PHP developer and you know better than I do.

**Comment by taufik-nurrohman** [comment]
https://github.com/mecha-cms/extend.feed/commit/9cdc25562bbacfe5ff5073912ab9a4e302db06e2
