### ISSUE TITLE
Strange Behavior: In the Case of HTML, The Content Disappears From Publishing

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#5]
Hello Developers,

I can observe strange behavior. I have created a new page and used it as "HTML". But after clicking "Publish" the content disappeared from the editor.

Hm ... I do not know where it comes from.

Do you have a tip or do I have to create all pages in Markdown?

Thanks in advance.

**Comment by ghost** [comment]
Today I gained an insight. It is so that when I work in the Markdown mode with German umlauts like "ä, ö, ü", they are then not displayed in the frontend. In HTML to write without the editor, it is somewhat tedious.

Will you bring out an extension that brings the finished WysiWyg editor or is there only the text editor with javascript?

Ideally it would be for a blogger a Wysiwyg editor in the admin interface when creating pages.

**Comment by ghost** [comment]
Now I have found the problem. If you change the configuration manually in the admin interface at "config", then the system is disabling and the creation of the pages is no longer possible.

I have now adjusted the confucuration directly in the config.php and see, there everything is in order.

Maybe you could look at it again.

It is "config" for editor in the admin interface.

**Comment by taufik-nurrohman** [comment]
The `v2.x.x` is currently unstable. That means, if you want to update something (core, extension, plugin, shield), then you will need to update everything including the core just to make sure that everything you use are up-to-date.

I will check this.

**Comment by taufik-nurrohman** [comment]
Yes, WYSIWYG is a _must_ for the GUI extension. A new good candidate for **Mecha** text editor next to **TinyMCE** and **CKEditor** is http://quilljs.com

**Comment by ghost** [comment]
Thanks, then I know now. I will wait with the next update of my Mecha installation. You are always developing.

This editor I did not know yet and it looks very good with it.
