### ISSUE TITLE
Route Pattern as Shell Pattern

### ISSUE THREAD

**Issue by taufik-nurrohman** [mecha-cms/genome#53]
I started to think that sticking up on the widely-used syntax is better than introducing new syntax. String format, date format and route pattern.

And for route pattern, it will be more logic to tell the user that it is just a _wildcard_ pattern as you normally see in the command prompt when searching for files.

~~~ .php
Route::set('foo/bar/**/[1-9][0-9]*', function() {}, 10);
~~~

**Comment by taufik-nurrohman** [comment]
The only problem with this plan is about how we can extract dynamic data from pattern. For example, in this pattern, what should be returned to the `$x` variable? Is it `abc` or `bc`?

~~~ .php
// Location: `http://127.0.0.1/abc/def/ghi`
Route::set('a*/def/ghi', function($x) {
    var_dump($x);
    exit;
});
~~~

My current solution is to ignore the existing wildcard pattern away and simply return each path segment to a single variable as an evaluated array:

~~~ .php
// Location: `http://127.0.0.1/abc/def/ghi`
Route::set('a*/def/ghi/123', function($x) {
    var_dump($x); // `['abc', 'def', 'ghi', 123]`
    exit;
});
~~~

**Comment by taufik-nurrohman** [comment]
To do pattern matching tasks, we can use the native PHP [`fnmatch`](https://www.php.net/manual/en/function.fnmatch.php) function with optional `GLOB_BRACE` pattern features that can be made separately.

**Comment by taufik-nurrohman** [comment]
~~**Update:** We probably don&rsquo;t need any route system.~~ NO!

~~~ .php
if (\fnmatch('/foo/*', $url->path)) {
    Hook::set('start', function() {}, 10);
}
~~~

**Comment by taufik-nurrohman** [comment]
And even simpler with native PHP features:

~~~ .php
if (\fnmatch('/foo/*', $url->path)) {
    \register_shutdown_function(function() {});
}
~~~

**Comment by taufik-nurrohman** [comment]
# **NO!**

**Comment by taufik-nurrohman** [comment]
**Idea 2:** Use _OctoberCMS_ route parameter style and pass its key to the `$this` scope in function closure:

~~~ .php
Route::set('article/tag/:id/*', function($data) {
    var_dump($this->id, $this[1]);
});
~~~

![cms@2x](https://user-images.githubusercontent.com/1669261/56220670-0614db80-6093-11e9-9bf2-28dafd8e9b63.png)

**Comment by tovic** [comment]
Changed to XML like syntax as how I usually describe placeholder for URL in my articles.

~~~ .php
Route::set('article/<year>/<month>/<slug>', function($form) {
    var_dump($this->year, $this->month, $this->slug);
});
~~~
