### ISSUE TITLE
In Which File I Need to Insert or Embed a Hook

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#6]
Hello Developers,

It is also noticeable to me today that the date will be updated on the blogposts that are created. So it is not so nice.

So I wanted to include the hook at http://mecha-cms.com/snippet/field-time-static. In which file are such hooks integrated?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Just put it in `index.php` or `index__.php` file that you see in the current shield, extension or plugin folder. Good luck!

**Comment by taufik-nurrohman** [comment]
For the default shield, it is still use `$page->update` property to show the date. You will need to use `$page->date->en_us` to show the hard-coded date. Example:

~~~ .html
<p><strong>Published on:</strong> <?php echo $page->date->en_us; ?></p>

**Comment by ghost** [comment]
Thank's for the Tipps.

So I found it out, because I could see in the index.php the other hook.
