### ISSUE TITLE
I Still Have Problems with the Search Snippet

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#7]
Hello Developers,

I can not handle the search snippet at http://mecha-cms.com/snippet/form-search. I have it as it is is embedded in the header.php.

In the frontend, only one search mask is displayed without the submit button. Check it out at http://mechacms.wpzweinull.ch/blog times.

How to search if no Submit button is displayed. It is understandable, however, that I must press "Enter". But maybe my blog readers see it differently.

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Look like you have just inserted the up-to-date version of the snippet in an old installed CMS (development) version. Because at that time we don&rsquo;t have `Form::submit()` method yet, it should returns nothing. But if you set the `DEBUG` constant in the `index.php` file to `true`, you should see a warning message that spells &ldquo;Method `Form::submit()` does not exist.&rdquo;.

**Comment by ghost** [comment]
Unfortunately still problems with the Search Snippet.

My header.php now looks partly so.

    <header>
      <h1>
        <?php if (!$url->path || $url->path === $site->slug): ?>
        <span><?php echo $site->title; ?></span>
        <?php else: ?>
        <a href="<?php echo $url; ?>"><?php echo $site->title; ?></a>
        <?php endif; ?>
      </h1>
      <p><?php echo $site->description; ?></p>
      <nav><?php Shield::get('nav'); ?></nav>

       <form action="<?php echo $site->is === 'page' ? Path::D($url->current) : $url->current; ?>" method="get">
    <?php echo Form::text($config->q, $site->search) . ' ' . Form::submit($language->search); ?>
    </form>
    </header>

Debug is active and does not show me any errors.

In the frontend I do not see the Submit button unfortunately. What am I doing wrong?

The Search Snippet I have newly integrated and taken from mecha-cms.com. My Mecha version is the last branch of GitHub.

**Comment by taufik-nurrohman** [comment]
Try to replace `Form::submit($language->search)` with `Form::submit('Test button')`.

**Comment by ghost** [comment]
The blog search with `?q=mechacms` worked well for me.

With the "Submit button" does not go unfortunately.

But ok, I have to communicate it to my readers as they can search the blog. I know it now.

**Comment by taufik-nurrohman** [comment]
~~~ .php
// Form::submit($name, $value, $text, $attr);
Form::submit(null, null, 'Test button');
~~~

**Comment by ghost** [comment]
Thanks, the Search Snippet I have now taken from mecha-cms.com. It works very well and the problem is done. Many Thanks.
