### ISSUE TITLE
I Would Like to Help with the Promotion of the Mecha CMS — Can You Please Create a Banner

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#8]
Hello @tovic ,

I've been following you and your work for a whole year now, working with Mecha v1.2.8 as well as now v2. I want to help more.

A possibility for me would be if you create for me a banner in the format 250x250 Px. This I then bind on the main blog https://internetblogger.de in the sidebar.

We need first German users to discover this CMS for themselves and I hope that I can motivate you somewhat.

Today I donated 15 euros to you and as soon as my PayPal account is recharged (takes only a few days) - then you will get this donation as soon as possible.

So create banners and I'll bind it. Then we look further 👍

**Comment by taufik-nurrohman** [comment]
Thanks a lot for your supports until now _sir_. I will need some help from my friend for this. Thanks again 😄

**Comment by ghost** [comment]
Hi @Tovic,

I like it very much. It takes only a few days until I sit on my own PC. Currently I am not at home and use a strange PC.

Then the donation goes to you. I can integrate the banner as soon as you send it to me.

I would also like the Mecha V2 CMS to grow and grow. Since I am already looking forward to everything that comes and what you develop.

**Comment by taufik-nurrohman** [comment]
This, as a starter.

![2017-03-28_194615](https://cloud.githubusercontent.com/assets/1669261/24408913/2af668ee-13f9-11e7-9712-ff914372411c.png)

More banners &rarr; http://mecha-cms.com/support/banner

**Comment by ghost** [comment]
Thanks for the banner. Now I have it under https://internetblogger.de in the right sidebar integrated. It looks very good and it is definitely clicked on.

I have a lot of projects on the internet and will integrate the banner on several projects in the sidebar so that more people will learn about Mecha CMS.

**Comment by taufik-nurrohman** [comment]
Thanks a lot.

**Comment by ghost** [comment]
Hi @Tovic,

Can you please tell me when you got the money via PayPal. Today, PayPal has lifted the amount from my bank and it should be credited to you in the next days in PayPal.

**Comment by taufik-nurrohman** [comment]
I sent you an email to power_sash[at]gmx.net

**Comment by ghost** [comment]
Thank you, I've understood everything. It still takes a few days with the payment, rather you can credit the PayPal. Then I wanted to make a second small payment. A little later, however.
