### ISSUE TITLE
Method Date::_() does not exist.

### ISSUE THREAD

**Issue by ghost** [mecha-cms/genome#9]
Hi @Tovic,

I have a tiny problem with the method "date". It does not seem to exist.

If you look at me at https://mechacms.wpzweinull.ch/blog/disqus-kommentare-in-mecha-cms-v2-mute at the bottom of the page, you see this.

How can I solve the problem.

I have of course downloaded the last version of Mecha v2 yesterday.

Thanks in advance.

![mechacms-method-date-nicht-existent](https://cloud.githubusercontent.com/assets/7885632/24387662/bc0edd4e-1376-11e7-980b-41c9e839e074.jpg)

**Comment by taufik-nurrohman** [comment]
My bad. Replace your code from `Date::_($baz)->foo_bar()` into `(new Date($baz))->foo_bar()`.

**Comment by ghost** [comment]
I need to ask you something else.

For me in the page.php it looks so. Unfortunately I find the code which you do not mean. You have to know that I'm not a developer and I'm trying to figure out what you're telling me.

Is this code correct in page.php?

    <footer>
      <p><?php echo $page->date->en_us; ?></p>
      <?php $update = Date::_($page->update); ?>
      <p><time datetime="<?php echo $update->W3C; ?>"><strong><?php echo $language->update; ?>:</strong> <?php echo $update->{str_replace('-', '_', $config->language)}; ?></time></p>
    </footer>

**Comment by ghost** [comment]
After hours of testing and testing, I have changed the code now.

    <footer>
    <p><?php echo $page->date->en_us; ?></p>
      <?php $update = (new Date($page))->update(); ?>
      <p><time datetime="<?php echo $update->W3C; ?>"><strong><?php echo $language->update; ?>:</strong> <?php echo $update->{str_replace('-', '_', $config->language)}; ?></time></p>
    </footer>

And I've updated all the pages including Home Page. The problem is now that the date of "1970" is displayed to me.

How can this fix?

Thanks in advance.

P.S.

The hook in the index.php looks like this.

    Hook::set('shield.before', function() use($site) {
    if ($page = Lot::get('page')) {
        $time = Path::F($page->path) . DS . 'time.data';
        if ($site->is !== '404' && !File::exist($time)) {
            File::write($page->time)->saveTo($time);
        }
    }
    });

**Comment by taufik-nurrohman** [comment]
~~~ .html
<footer>
  <p><?php echo $page->date->en_us; ?></p>
  <?php $update = new Date($page->update); ?>
  <p><time datetime="<?php echo $update->W3C; ?>"><strong><?php echo $language->update; ?>:</strong> <?php echo $update->en_us; ?></time></p>
</footer>
~~~

**Comment by ghost** [comment]
I am very glad that you help me so much. Unfortunately, I am not a web developer.

Now the thing works with "Date and Time". Thank you!
